find_package(OpenMP QUIET)

set(TARGET llama-tts)
add_executable(${TARGET} tts.cpp outetts/outetts.cpp)
target_link_libraries(${TARGET} PRIVATE llama llama-common omtd ${CMAKE_THREAD_LIBS_INIT})
if(OpenMP_CXX_FOUND)
    target_link_libraries(${TARGET} PRIVATE OpenMP::OpenMP_CXX)
endif()
target_compile_features(${TARGET} PRIVATE cxx_std_17)

set(TARGET llama-higgs-probe)
add_executable(${TARGET} higgs_v3/higgs-main.cpp)
target_link_libraries(${TARGET} PRIVATE omtd ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)

set(TARGET llama-higgs-tts)
add_executable(${TARGET} higgs_v3/higgs-main.cpp)
target_link_libraries(${TARGET} PRIVATE omtd ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)

set(TARGET llama-higgs-reference-encode)
add_executable(${TARGET} higgs_v3/higgs-reference-encode.cpp)
target_link_libraries(${TARGET} PRIVATE llama ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)
if(OpenMP_CXX_FOUND)
    target_link_libraries(${TARGET} PRIVATE OpenMP::OpenMP_CXX)
endif()
if(MSVC)
    target_compile_options(${TARGET} PRIVATE /bigobj)
endif()

if(LLAMA_TOOLS_INSTALL)
    install(TARGETS llama-tts llama-higgs-probe llama-higgs-tts llama-higgs-reference-encode RUNTIME)
endif()
